# Generated by Django 3.2.16 on 2023-04-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230430_1325'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientsquantity',
            name='recipes_ingredient',
        ),
        migrations.AddConstraint(
            model_name='ingredientsquantity',
            constraint=models.UniqueConstraint(fields=('recipes', 'ingredients'), name='recipes_ingredient'),
        ),
    ]
